
notifications:
  slack: healthsafe:yjWOO4vhSSuvJ4g9ehyYXyxF

    - language: android
      android:
        update_sdk: true
        components:
          - tools
          - build-tools-24.0.1
          - android-24
          - platform-tools
          - extra-android-support # because I'm use support library
          - extra-android-m2repository # because I'm use support library
          - $ANDROID_TARGET
          - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
        licenses:
          - '.+'

      sudo: required

      jdk:
        - oraclejdk8

      install: true

      before_script:
      #  - chmod +x ./gradlew

      script:
      #  - ./gradlew testDebugUnitTest
      #  - ./gradlew createDebugCoverageReport
      #  - ./codacy-coverage-reporter report -l Java -r ./app/build/reports/coverage/debug/report.xml

      before_install:
        - pip install --user codecov
      after_success:
      #  - codecov
        - bash <(curl -s https://codecov.io/bash)
